<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260805153314 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE workflow (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, description TEXT NOT NULL, trigger_type VARCHAR(20) NOT NULL, trigger_config JSON NOT NULL, parameters_schema JSON NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_65C598165E237E06 ON workflow (name)');
        $this->addSql('CREATE TABLE workflow_execution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, input_data JSON NOT NULL, output_data JSON NOT NULL, status VARCHAR(20) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, error_message TEXT NOT NULL, execution_log JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, workflow_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FF094DBF2C7C2CBA ON workflow_execution (workflow_id)');
        $this->addSql('CREATE TABLE workflow_step (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, step_type VARCHAR(20) NOT NULL, "order" INT NOT NULL, configuration JSON NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, workflow_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_626EE072C7C2CBA ON workflow_step (workflow_id)');
        $this->addSql('CREATE UNIQUE INDEX workflow_step_order_unique ON workflow_step (workflow_id, "order")');
        $this->addSql('ALTER TABLE workflow_execution ADD CONSTRAINT FK_FF094DBF2C7C2CBA FOREIGN KEY (workflow_id) REFERENCES workflow (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workflow_step ADD CONSTRAINT FK_626EE072C7C2CBA FOREIGN KEY (workflow_id) REFERENCES workflow (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE workflow_execution DROP CONSTRAINT FK_FF094DBF2C7C2CBA');
        $this->addSql('ALTER TABLE workflow_step DROP CONSTRAINT FK_626EE072C7C2CBA');
        $this->addSql('DROP TABLE workflow');
        $this->addSql('DROP TABLE workflow_execution');
        $this->addSql('DROP TABLE workflow_step');
    }
}
