<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Multi-user auth: app_user table, plus user/triggered_by attribution on
 * conversation/workflow_execution. Seeds one app_user row from the previous
 * single shared admin account (same email/hash as ADMIN_USERNAME /
 * ADMIN_PASSWORD_HASH in .env) so existing HTTP Basic clients (the Nuxt
 * frontend proxy) keep authenticating without any credential change.
 */
final class Version20260806214903 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add app_user table and user/triggered_by attribution on conversation/workflow_execution';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_APP_USER_EMAIL ON app_user (email)');

        $this->addSql('ALTER TABLE conversation ADD user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_CONVERSATION_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_CONVERSATION_USER ON conversation (user_id)');

        $this->addSql('ALTER TABLE workflow_execution ADD triggered_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE workflow_execution ADD CONSTRAINT FK_WORKFLOW_EXECUTION_TRIGGERED_BY FOREIGN KEY (triggered_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_WORKFLOW_EXECUTION_TRIGGERED_BY ON workflow_execution (triggered_by_id)');

        // Carry the previous single shared admin account over as the first
        // app_user row, same email/hash, so existing HTTP Basic clients keep working.
        $this->addSql(<<<'SQL'
            INSERT INTO app_user (email, password, roles, is_active, created_at, updated_at)
            VALUES ('admin', '$2y$13$iS.GDAyZPNrxSiwSv1l4Tu5KtBH/sHZYckqrEO00NF4qzvaGJCQRC', '["ROLE_ADMIN"]', true, NOW(), NOW())
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE conversation DROP CONSTRAINT FK_CONVERSATION_USER');
        $this->addSql('DROP INDEX IDX_CONVERSATION_USER');
        $this->addSql('ALTER TABLE conversation DROP user_id');

        $this->addSql('ALTER TABLE workflow_execution DROP CONSTRAINT FK_WORKFLOW_EXECUTION_TRIGGERED_BY');
        $this->addSql('DROP INDEX IDX_WORKFLOW_EXECUTION_TRIGGERED_BY');
        $this->addSql('ALTER TABLE workflow_execution DROP triggered_by_id');

        $this->addSql('DROP TABLE app_user');
    }
}
