<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Hand-written, not generated by doctrine:migrations:diff -- same tooling
 * gap as Version20260807160000 (diff/introspection throws on this
 * ORM/DBAL/doctrine-bridge combination), not specific to this column.
 */
final class Version20260808220000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add message.feedback (thumbs up/down)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE message ADD feedback VARCHAR(10) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE message DROP feedback');
    }
}
