<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260805160551 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ai_agent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, description TEXT NOT NULL, system_prompt TEXT NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7A3CA7D85E237E06 ON ai_agent (name)');
        $this->addSql('CREATE TABLE ai_agent_workflow (ai_agent_id INT NOT NULL, workflow_id INT NOT NULL, PRIMARY KEY (ai_agent_id, workflow_id))');
        $this->addSql('CREATE INDEX IDX_812831432BF2F76B ON ai_agent_workflow (ai_agent_id)');
        $this->addSql('CREATE INDEX IDX_812831432C7C2CBA ON ai_agent_workflow (workflow_id)');
        $this->addSql('CREATE TABLE conversation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(10) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, metadata JSON NOT NULL, conversation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6BD307F9AC0396 ON message (conversation_id)');
        $this->addSql('ALTER TABLE ai_agent_workflow ADD CONSTRAINT FK_812831432BF2F76B FOREIGN KEY (ai_agent_id) REFERENCES ai_agent (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ai_agent_workflow ADD CONSTRAINT FK_812831432C7C2CBA FOREIGN KEY (workflow_id) REFERENCES workflow (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE collection ADD agent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE collection ADD CONSTRAINT FK_FC4D65323414710B FOREIGN KEY (agent_id) REFERENCES ai_agent (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FC4D65323414710B ON collection (agent_id)');
        $this->addSql('ALTER TABLE workflow_execution ADD conversation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE workflow_execution ADD CONSTRAINT FK_FF094DBF9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_FF094DBF9AC0396 ON workflow_execution (conversation_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ai_agent_workflow DROP CONSTRAINT FK_812831432BF2F76B');
        $this->addSql('ALTER TABLE ai_agent_workflow DROP CONSTRAINT FK_812831432C7C2CBA');
        $this->addSql('ALTER TABLE message DROP CONSTRAINT FK_B6BD307F9AC0396');
        $this->addSql('DROP TABLE ai_agent');
        $this->addSql('DROP TABLE ai_agent_workflow');
        $this->addSql('DROP TABLE conversation');
        $this->addSql('DROP TABLE message');
        $this->addSql('ALTER TABLE collection DROP CONSTRAINT FK_FC4D65323414710B');
        $this->addSql('DROP INDEX UNIQ_FC4D65323414710B');
        $this->addSql('ALTER TABLE collection DROP agent_id');
        $this->addSql('ALTER TABLE workflow_execution DROP CONSTRAINT FK_FF094DBF9AC0396');
        $this->addSql('DROP INDEX IDX_FF094DBF9AC0396');
        $this->addSql('ALTER TABLE workflow_execution DROP conversation_id');
    }
}
