<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260805121045 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE collection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, description TEXT NOT NULL, is_common BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, vector_index_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FC4D65325E237E06 ON collection (name)');
        $this->addSql('CREATE INDEX IDX_FC4D65321214F412 ON collection (vector_index_id)');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, description TEXT NOT NULL, file_path VARCHAR(255) DEFAULT NULL, file_type VARCHAR(10) NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, file_size INT NOT NULL, status VARCHAR(20) NOT NULL, processing_error TEXT NOT NULL, metadata JSON NOT NULL, category_id INT DEFAULT NULL, collection_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A7612469DE2 ON document (category_id)');
        $this->addSql('CREATE INDEX IDX_D8698A76514956FD ON document (collection_id)');
        $this->addSql('CREATE TABLE document_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_898DE8985E237E06 ON document_category (name)');
        $this->addSql('CREATE TABLE document_chunk (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, chunk_index INT NOT NULL, start_position INT NOT NULL, end_position INT NOT NULL, vector_id VARCHAR(64) DEFAULT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FCA7075CC33F7837 ON document_chunk (document_id)');
        $this->addSql('CREATE UNIQUE INDEX document_chunk_index_unique ON document_chunk (document_id, chunk_index)');
        $this->addSql('CREATE TABLE faq (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, question VARCHAR(500) NOT NULL, answer TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, tags JSON NOT NULL, category_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E8FF75CC12469DE2 ON faq (category_id)');
        $this->addSql('ALTER TABLE collection ADD CONSTRAINT FK_FC4D65321214F412 FOREIGN KEY (vector_index_id) REFERENCES vector_index (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A7612469DE2 FOREIGN KEY (category_id) REFERENCES document_category (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76514956FD FOREIGN KEY (collection_id) REFERENCES collection (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document_chunk ADD CONSTRAINT FK_FCA7075CC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE faq ADD CONSTRAINT FK_E8FF75CC12469DE2 FOREIGN KEY (category_id) REFERENCES document_category (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE collection DROP CONSTRAINT FK_FC4D65321214F412');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A7612469DE2');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76514956FD');
        $this->addSql('ALTER TABLE document_chunk DROP CONSTRAINT FK_FCA7075CC33F7837');
        $this->addSql('ALTER TABLE faq DROP CONSTRAINT FK_E8FF75CC12469DE2');
        $this->addSql('DROP TABLE collection');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE document_category');
        $this->addSql('DROP TABLE document_chunk');
        $this->addSql('DROP TABLE faq');
    }
}
