<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260805115432 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE search_query (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, query VARCHAR(500) NOT NULL, results_count INT NOT NULL, execution_time DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, metadata JSON NOT NULL, vector_index_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_108876021214F412 ON search_query (vector_index_id)');
        $this->addSql('CREATE TABLE vector_index (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT NOT NULL, collection_id VARCHAR(100) NOT NULL, dimension INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN NOT NULL, metadata JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CF0BAC805E237E06 ON vector_index (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CF0BAC80514956FD ON vector_index (collection_id)');
        $this->addSql('ALTER TABLE search_query ADD CONSTRAINT FK_108876021214F412 FOREIGN KEY (vector_index_id) REFERENCES vector_index (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE search_query DROP CONSTRAINT FK_108876021214F412');
        $this->addSql('DROP TABLE search_query');
        $this->addSql('DROP TABLE vector_index');
    }
}
